# -*- coding: utf-8 -*-
"""split.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ozx_zWIaDMOcokU6mY8p6NfoChkj87QM
"""

from google.colab import drive
drive.mount('/content/gdrive')

import tensorflow as tf
import pandas as pd
import PIL
import os
import shutil
from shutil import copyfile
import matplotlib.pyplot as plt

base_folder='/content/gdrive/MyDrive/CUB_200_2011/CUB_200_2011'
image_txt_path=base_folder+'/images.txt'
train_test_split_path=base_folder+'/train_test_split.txt'
images_path=base_folder+'/images/'
test_f='/content/gdrive/MyDrive/images1/test_set'
train_f='/content/gdrive/MyDrive/images1/train_set'

def ignore_files(dir,files): return [f for f in files if os.path.isfile(os.path.join(dir,f))]

shutil.copytree(images_path,test_f,ignore=ignore_files)
shutil.copytree(images_path,train_f,ignore=ignore_files)
with open(image_txt_path) as f:
  images_lines=f.readlines()
with open(train_test_split_path) as f:
  split_lines=f.readlines()
test_images,train_images=0,0

for image_line,split_line in zip(images_lines,split_lines):
  image_line=(image_line.strip()).split(' ')
  split_line=(split_line.strip()).split(' ')
  image=plt.imread(images_path+image_line[1])
  if len(image.shape)==3:
    if int(split_line[1] == '0'):
      copyfile(images_path+image_line[1],test_f+'/'+image_line[1])
      print(test_images)
      test_images+=1
    else:
      copyfile(images_path+image_line[1],train_f+'/'+image_line[1])
      print(train_images)
      train_images+=1

print(train_images,test_images)
assert train_images==5990
assert test_images==5790

print('Dataset successfully splitted')

